### ISSUE TITLE
Добавить 2 раздел с "Пресеты не tree"

### ISSUE THREAD

**Issue by Lyumih** [hyoo-ru/tree.hyoo.ru#24]
Ссылка на тред в телеграм: https://t.me/mam_mol/121847

Проблема: 
- Трии песочница получается очень мощной, что можно делать переводы форматов не только, где начальный и конечный формат .tree.
Пример: json -> XML. 
https://tree.hyoo.ru/#!pipeline=%24mol_json_from_string~%24mol_tree2_from_json~%24mol_tree2_xml_to_text~%24mol_tree2_text_to_string/source=%7B%22foo%22%3A%5B%22bar%22%5D%7D

Сейчас собраны пресеты только для tree
Инструкция - добавлять новые пресеты, которые не связаны с tree в начале и вконце формата, после всех пресетов, которые связаны с tree.

<img width="1660" alt="Снимок экрана 2023-03-22 в 09 59 08" src="https://user-images.githubusercontent.com/32732179/226825757-0300825c-11e3-4015-acb5-22a50fd22530.png">

**Comment by nin-jin** [comment]
Не сказал бы, что JSON=>XML  - это нужный функционал. Так, побаловаться.
